### ISSUE TITLE
 iOS11 微信内视频主区中播放按钮不显示

### ISSUE THREAD

**Issue by andycsp** [ireaderlab/zyMedia#11]
examples/video.html 页面在 iOS11 微信内视频主区中播放按钮不显示；在Android 手机微信内可以显示。希望尽快帮助看一下。谢谢。

iOS 11微信内截图
![ios11](https://user-images.githubusercontent.com/7963719/31656430-1f2a3c0c-b35e-11e7-8db3-b96b9b19122a.png)

Android微信内截图
![android](https://user-images.githubusercontent.com/7963719/31656456-2d73c940-b35e-11e7-96f6-e0961fb3e38e.png)

**Comment by avajayam** [comment]
已改，仅iOS 9-下的iPhone自动隐藏大按钮，以避免和safari原生的大按钮重复 [063f408](https://github.com/ireaderlab/zyMedia/commit/063f408854ea53f9e72e2bb069790f60492bccab)

**Comment by andycsp** [comment]
@avajayam 收到，谢谢您的帮助。
