### ISSUE TITLE
IOS10.3.3，iphone6 plus点击播放也是一直加载，有时候播放了还调用系统播放器

### ISSUE THREAD

**Issue by zbenj** [ireaderlab/zyMedia#12]
IOS10.3.3，iphone6 plus点击播放也是一直加载，有时候加载了很长时间播放了还调用系统播放器

**Comment by zbenj** [comment]
视频源是本地视频，安卓手机正常，电脑正常

**Comment by avajayam** [comment]
加载慢（边下载数据边解码）原因比较多，网络，视频大小，手机或浏览器解码能力。iOS10的确还有系统UI，这个暂时没办法解决。
