### ISSUE TITLE
rtmp协议的视频不能播放吗？

### ISSUE THREAD

**Issue by objectboy2016** [ireaderlab/zyMedia#13]
![image](https://user-images.githubusercontent.com/16741598/43949420-035e4aee-9cc0-11e8-8d36-cf79c541cb1f.png)

**Comment by avajayam** [comment]
rtmp目前看只有Flash支持，[mdn](https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Audio_and_video_delivery/Live_streaming_web_audio_and_video)

**Comment by objectboy2016** [comment]
请问有没有计划支持呢？

**Comment by avajayam** [comment]
没有
