### ISSUE TITLE
hideVideoControlsOnLoad: false

### ISSUE THREAD

**Issue by codeliufan** [ireaderlab/zyMedia#14]
hideVideoControlsOnLoad: false
加载时是否显示视频控制栏，默认否，true为显示

实际用了下，默认加载时控制条为显示，设置为true时才隐藏了

**Comment by avajayam** [comment]
感谢，已修改 [399c42c](https://github.com/ireaderlab/zyMedia/commit/399c42c04cea568d358a9419d00695ef9e1be55c)
