### ISSUE TITLE
多段视频全屏时错位

### ISSUE THREAD

**Issue by wanglichao1** [ireaderlab/zyMedia#3]
视频列表
![qq 20161102185023](https://cloud.githubusercontent.com/assets/20577949/19926046/727bbdac-a12d-11e6-8aea-0b8e3b2fbeb5.jpg)
全屏时
![qq 20161102185014](https://cloud.githubusercontent.com/assets/20577949/19926066/8ae07dba-a12d-11e6-8b00-7fda392fa4cb.jpg)

**Comment by avajayam** [comment]
@逆水寒反馈的，等oneplus2机型验证

ua：Mozilla/5.0 (Linux; Android 6.0.1; ONE A2001 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/47.0.2526.100 Mobile Safari/537.36

**Comment by zack-tu** [comment]
这个怎么解决的？？同样遇到了这个问题，在安卓APP上普遍存在

**Comment by avajayam** [comment]
这个一直没机会验证，看截图是全屏黑底样式没覆盖住其他视频。正常全屏时，浏览器是会自己在.zy_media上加个全屏定位样式，以覆盖其他页面元素的

**Comment by dandelion-Chen** [comment]
试下在源代码中的e.media.style.height=e.container.style.height="100%"的后面加入
e.media.style.zIndex=e.container.style.zIndex="1001"

然后在将css添加
.zy_controls{
    z-index:1002
}

**Comment by avajayam** [comment]
已改，乐视手机 乐pro3 Android 6.0.1 app内也复现了 #095b78d
