### ISSUE TITLE
如何切换视频url呢

### ISSUE THREAD

**Issue by yuezheng2006** [ireaderlab/zyMedia#4]

**Comment by avajayam** [comment]
直接替换视频的poster和src，比如

&lt;div class="zy_media"&gt;
    &lt;video poster="test.jpg" data-config='{"mediaTitle": "《疯狂动物城》--腾讯视频"}'&gt;
        &lt;source src="test.mp4" type="video/mp4"&gt;
        您的浏览器不支持HTML5视频
    &lt;/video&gt;
&lt;/div&gt;

&lt;div data-js="btn" style="width: 100px; height: 50px; background: #0f0"&gt;&lt;/div&gt;


&lt;script src="zy.media.min.js"&gt;&lt;/script&gt;
&lt;script&gt;

    zymedia('video');

    document.querySelector('[data-js=btn]').addEventListener('click', function(){
        var _video = document.querySelector('video');
        _video.src = 'test2.mp4';
        _video.setAttribute('poster', 'test2.jpg');
        _video.play()
    })

&lt;/script&gt;
