### ISSUE TITLE
如下面的这种方式读取，在iOS Safari浏览器上播放不了，求解答

### ISSUE THREAD

**Issue by lewis180777** [ireaderlab/zyMedia#5]
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
<title>掌阅--媒体播放器</title>
<link rel="stylesheet" href="zy.media.min.css">
</head>
<body>

<div class="zy_media">
    <video poster="test.jpg" data-config='{"mediaTitle": "《疯狂动物城》--腾讯视频"}'>
        <source src="http://dev.xinhua-news.com:8080/xhs-web-mall/player/ecpshowflash?videoUUId=5817609c45ce5b7beb630899&fileSize=" type="video/mp4">
        您的浏览器不支持HTML5视频
    </video>
</div>

<script src="zy.media.min.js"></script>
<script>

    zymedia('video');

</script>

</body>
</html>

**Comment by avajayam** [comment]
视频源的问题，偏大
