### ISSUE TITLE
安卓重力感应全屏问题

### ISSUE THREAD

**Issue by dzjwan521** [ireaderlab/zyMedia#9]
安卓手机竖屏状态点击全屏没有问题,竖着铺满整个屏幕,,,
但用户肯定希望全屏播放   ,当我横屏时(此时是竖屏全屏),video高度出现问题  变得很小
只有在我手机进入页面是横屏时候  点击全屏才会正常

**Comment by Thyiad** [comment]
@dzjwan521 这个横屏解决了吗？

**Comment by avajayam** [comment]
已经改了，详见[b841ece](https://github.com/ireaderlab/zyMedia/commit/b841eceb08c0a2b56617b65711443b9a178d3d5b)
